import uuid

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import relationship

from app.db.base import Base


class Event(Base):
    """
    ORM model for calendar events.
    """

    __tablename__ = "events"

    # Primary key: autogenerated UUID
    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Title and description
    title = Column(String(length=100), nullable=False)
    description = Column(Text, nullable=True)

    # Start and end timestamps
    start_time = Column(DateTime(timezone=True), nullable=False)
    end_time = Column(DateTime(timezone=True), nullable=False)

    # Recurrence flags
    is_recurring = Column(Boolean, nullable=False, default=False)
    recurrence_pattern = Column(String(length=100), nullable=True)

    # Owner FK → users.id
    owner_id = Column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    owner = relationship("User", back_populates="events")

    # Permissions and history relationships
    permissions = relationship(
        "Permission", back_populates="event", cascade="all, delete-orphan"
    )
    histories = relationship(
        "History", back_populates="event", cascade="all, delete-orphan"
    )
